
pp13TeVPrompt:
    Particle: "Dstar"
    FixSigma: 0
    SigmaFile: ""
    FixSigmaRatio: 0 # used only if SgnFunc = k2GausSigmaRatioPar
    SigmaRatioFile: ""
    SigmaMultFactor: 1. #float or MinusUnc, PlusUnc
    FixMean: 0
    BoundMean: 0 # 0: Do not set limits on mean range, 1: the mean is set to be between MassMin[i] and MassMax[i]
    MeanFile: ""
    PtMin: [1., 2., 4., 6., 8.,  12.]
    PtMax: [2., 4., 6., 8., 12., 50.]
    MassMin: [0.1396, 0.1396, 0.1396, 0.1396, 0.1396, 0.1396]
    MassMax: [0.16, 0.16, 0.16, 0.16, 0.16, 0.16]
    Rebin: [4, 4, 4, 4, 4, 4]
    InclSecPeak: [0, 0, 0, 0, 0, 0] # Ds only
    SigmaSecPeak: [0, 0, 0, 0, 0, 0] # Ds only
    SigmaFileSecPeak: 0 # Ds only
    SigmaMultFactorSecPeak: 0 # Ds only
    FixSigmaToFirstPeak: 0
    UseLikelihood: 0
    BkgFunc: ["kPowEx", "kPowEx", "kPowEx", "kPowEx", "kPowEx", "kPowEx"]
    SgnFunc: ["kGaus", "kGaus", "kGaus", "kGaus", "kGaus", "kGaus"]
    FixSigmaRatio: 0 # used only if SgnFunc = k2GausSigmaRatioPar
    SigmaRatioFile: "/data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/applied_050122_v2/merged/ry_mc_basic_PromptEn.root"
    EnableRef: false

pp13TeVFD:
    Particle: "Dstar"
    FixSigma: 1
    SigmaFile: "/home/lvermunt/FemtoAnalysis/Analysis_output/HM_Opti0306_v151022/RawYield_Dstar_data_HM_Opti0306.root"
    FixSigmaRatio: 0 # used only if SgnFunc = k2GausSigmaRatioPar
    SigmaRatioFile: ""
    SigmaMultFactor: 1. #float or MinusUnc, PlusUnc
    FixMean: 0
    BoundMean: 0 # 0: Do not set limits on mean range, 1: the mean is set to be between MassMin[i] and MassMax[i]
    MeanFile: ""
    PtMin: [1., 2., 4., 6., 8.,  12.]
    PtMax: [2., 4., 6., 8., 12., 50.]
    MassMin: [0.1396, 0.1396, 0.1396, 0.1396, 0.1396, 0.1396]
    MassMax: [0.16, 0.16, 0.16, 0.16, 0.16, 0.16]
    Rebin: [4, 4, 4, 4, 4, 4]
    InclSecPeak: [0, 0, 0, 0, 0, 0] # Ds only
    SigmaSecPeak: [0, 0, 0, 0, 0, 0] # Ds only
    SigmaFileSecPeak: 0 # Ds only
    SigmaMultFactorSecPeak: 0 # Ds only
    FixSigmaToFirstPeak: 0
    UseLikelihood: 0
    BkgFunc: ["kPowEx", "kPowEx", "kPowEx", "kPowEx", "kPowEx", "kPowEx" ]
    SgnFunc: ["kGaus", "kGaus", "kGaus", "kGaus", "kGaus", "kGaus"]
    FixSigmaRatio: 0 # used only if SgnFunc = k2GausSigmaRatioPar
    SigmaRatioFile: "rawYields/ry_mc_basic_PromptEn.root"
    EnableRef: false

