infiles:
    signal:
        prompt:
            filename:
                [
                   /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt1_2/Prompt_pT_1_2_ModelApplied.parquet.gzip,
                   /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt2_4/Prompt_pT_2_4_ModelApplied.parquet.gzip,
                   /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt4_6/Prompt_pT_4_6_ModelApplied.parquet.gzip,
                   /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt6_8/Prompt_pT_6_8_ModelApplied.parquet.gzip,
                   /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt8_12/Prompt_pT_8_12_ModelApplied.parquet.gzip,
                   /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt12_50/Prompt_pT_12_50_ModelApplied.parquet.gzip
                ]
            dirname: null
            treename: null
        feeddown:
            filename:
                [
                   /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt1_2/FD_pT_1_2_ModelApplied.parquet.gzip,
                   /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt2_4/FD_pT_2_4_ModelApplied.parquet.gzip,
                   /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt4_6/FD_pT_4_6_ModelApplied.parquet.gzip,
                   /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt6_8/FD_pT_6_8_ModelApplied.parquet.gzip,
                   /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt8_12/FD_pT_8_12_ModelApplied.parquet.gzip,
                   /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt12_50/FD_pT_12_50_ModelApplied.parquet.gzip
                ]
            dirname: null
            treename: null
    secpeak: # only for Ds
        prompt:
            filename: null
            dirname: null
            treename: null
        feeddown:
            filename: null
            dirname: null
            treename: null
        mean: 0 # fixed values of mean and sigma, used if histogram is not provided
        sigma: 0
    background:
        filename:
            [
               /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt1_2/Data_pT_1_2_ModelApplied.parquet.gzip,
               /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt2_4/Data_pT_2_4_ModelApplied.parquet.gzip,
               /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt4_6/Data_pT_4_6_ModelApplied.parquet.gzip,
               /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt6_8/Data_pT_6_8_ModelApplied.parquet.gzip,
               /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt8_12/Data_pT_8_12_ModelApplied.parquet.gzip,
               /home/lvermunt/FemtoAnalysis/ML_Training/Dstar_050122_v2_HypOpt/pt12_50/Data_pT_12_50_ModelApplied.parquet.gzip
            ]
        dirname: null
        treename: null
        #NB: nEvents and fractiontokeep are not trivial because of downsampling
        nEvents: 1000000000 # number of events for bkg in dataframe
        downscalefraction: [0.15] #[0.002, 0.002, 0.01, 0.15, 1, 1]
        fractiontokeep: [1, 1, 1, 1, 1, 1]
        isMC: false # if false bkg from SB
        fitFunc: expopow # fit function for bkg from SB, e.g. pol1, pol2, expo
        nSigma: 4 # number of sigma from signal region, used to select SB
        corrfactor:
            filename: null # set null if no MC bkg correction is needed
            histoname: null

    #No preselection efficiency = assume 1 (which is fine in case of exp. signf. in arb. units)
    preseleff:
        filename: /home/lvermunt/FemtoAnalysis/DmesonAnalysis/optimisation/preSelEfficiency_Dstar_MC_20161718_HM_Opti.root
        prompthistoname: hEffPrompt
        feeddownhistoname: hEffFD
    acceptance: /home/lvermunt/FemtoAnalysis/DmesonAnalysis/accfiles/Acceptance_Toy_DStarD0pi_yfidPtDep_etaDau09_ptDau100_promptDstarFONLL13ptshape_FONLLy.root

ppRefFile: null

predictions:
    crosssec:
        filename: /home/lvermunt/FemtoAnalysis/DmesonAnalysis/models/fonll/feeddown/DmesonLcPredictions_13TeV_y05_FFee_BRpythia8_SepContr_PDG2020.root
        histonames:
            prompt: hDstarD0pipred_central
            feeddown: hDstarD0pifromBpred_central_corr
    Raa:
        prompt: 1. # can either be a fixed value or a text file
        feeddown: 1. # can either be a fixed value or a text file
        model: null

nExpectedEvents: 1000000000
sigmaMB: 57.8e+9 #pb
Taa: 1.

#To estimate expected signal from FONLL predictions
expectedSignalFrom: "prompt" # Choice between: 'prompt' or 'feeddown'

ptmin: [6] #[1, 2, 4, 6, 8, 12]
ptmax: [8] #[2, 4, 6, 8, 12, 50]

#for fitting. If not present, takes first and last bin (not OK for these Dstar fit)
minMass: 0.139571 #0.1395
maxMass: 0.24 #0.20

#Extra feature, not neseccary for this Dstar analysis
dfparametercuts:
    name: null
    min: null
    max: null
    enable: False # enable cuts over df column query over each df and relative scan histos

#Vary BKG and prompt like Dplus femto analysis
cutvars: # prompt
    ML_output_Bkg:
        axisnum: null
        min: [0.07] #[0.09, 0.15, 0.05, 0.07, 0.10, 0.18] #[0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
        max: [0.40] #[0.15, 0.26, 0.17, 0.40, 0.40, 0.60] #[0.20, 0.30, 0.30, 0.30, 0.30, 0.60]
        step: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001] #[0.00167, 0.0025, 0.0025, 0.0025, 0.0025, 0.005]
        upperlowercut: Upper
    ML_output_Prompt:
        axisnum: null
        min: [0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        max: [0.30, 0.30, 0.30, 0.30, 0.30, 0.30] #[0.50, 0.50, 0.50, 0.50, 0.50, 0.50]
        step: [0.005, 0.005, 0.005, 0.005, 0.005, 0.005]
        upperlowercut: Lower
