isMC: no
filename: [/data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_0/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_10/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_11/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_12/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_13/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_14/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_15/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_16/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_17/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_18/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_19/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_1/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_20/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_21/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_22/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_23/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_24/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_25/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_26/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_27/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_28/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_29/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_2/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_30/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_31/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_32/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_33/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_34/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_35/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_36/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_3/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_4/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_5/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_6/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_7/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_8/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_10/pack_9/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_11/pack_0/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_12/pack_0/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_12/pack_1/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_12/pack_2/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_12/pack_3/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_12/pack_4/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_12/pack_5/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_12/pack_6/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_12/pack_7/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_12/pack_8/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_0/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_10/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_11/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_12/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_13/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_14/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_15/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_16/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_17/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_1/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_2/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_3/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_4/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_5/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_6/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_7/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_8/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_13/pack_9/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_14/pack_0/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_1/pack_0/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_1/pack_1/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_1/pack_2/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_1/pack_3/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_1/pack_4/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_1/pack_5/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_1/pack_6/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_1/pack_7/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_1/pack_8/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_1/pack_9/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_2/pack_0/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_2/pack_1/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_2/pack_2/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_2/pack_3/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_2/pack_4/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_2/pack_5/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_2/pack_6/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_2/pack_7/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_2/pack_8/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_2/pack_9/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_3/pack_0/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_3/pack_10/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_3/pack_11/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_3/pack_12/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_3/pack_13/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_3/pack_14/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_3/pack_15/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_3/pack_1/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_3/pack_2/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_3/pack_3/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_3/pack_4/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_3/pack_5/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_3/pack_6/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_3/pack_7/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_3/pack_8/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_3/pack_9/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_4/pack_0/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_5/pack_0/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_6/pack_0/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_7/pack_0/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_8/pack_0/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_8/pack_1/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_9/pack_0/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_9/pack_10/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_9/pack_11/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_9/pack_12/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_9/pack_13/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_9/pack_14/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_9/pack_15/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_9/pack_1/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_9/pack_2/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_9/pack_3/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_9/pack_4/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_9/pack_5/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_9/pack_6/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_9/pack_7/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_9/pack_8/AnalysisResults.root,
           /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/merged/child_9/pack_9/AnalysisResults.root]
dirname: PWGHF_D2H_TreeDstartoD0piLoose_HM_Opti
listname: coutputTreeDstartoD0piLoose_HM_Opti
sparsenameAll: fnSparse
enableRef: no #always no for data
enableSecPeak: no #always no for data
normname: NormalizationCounter
histoevname: hNEvents

#info for trees (files can be different if trees are filtered or with applied ML models)
tree:
    particle: Dstar #needed to define binning for invariant-mass histo
    filenameAll: [/data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/applied_210122_v1/merged/Data_pT_1_2_ModelApplied.parquet.gzip,
                  /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/applied_210122_v1/merged/Data_pT_2_4_ModelApplied.parquet.gzip,
                  /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/applied_210122_v1/merged/Data_pT_4_6_ModelApplied.parquet.gzip,
                  /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/applied_210122_v1/merged/Data_pT_6_8_ModelApplied.parquet.gzip,
                  /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/applied_210122_v1/merged/Data_pT_8_12_ModelApplied.parquet.gzip,
                  /data/TTree/DstarFemto/vAN-20220110_ROOT6-1/pp_data/668_20220113-1011/applied_210122_v1/merged/Data_pT_12_50_ModelApplied.parquet.gzip
                  ]
    dirname: null
    treename: null

