rawyields:
    inputdir: ../Analysis_output/HM_Opti0306_v161022/CutVar_Opti0306_small/
    inputfiles: [
            RawYieldsDstar_ML_outFD_neg01.root,
            RawYieldsDstar_ML_outFD_neg02.root,
            RawYieldsDstar_ML_outFD_neg03.root,
            RawYieldsDstar_ML_outFD_neg04.root,
            RawYieldsDstar_ML_outFD_neg05.root,
            RawYieldsDstar_ML_outFD_neg06.root,
            RawYieldsDstar_ML_outFD_neg07.root,
            RawYieldsDstar_ML_outFD_neg08.root,
            RawYieldsDstar_ML_outFD_neg09.root,
            RawYieldsDstar_ML_outFD_neg10.root,
            RawYieldsDstar_ML_outFD_pos01.root,
            RawYieldsDstar_ML_outFD_pos02.root,
            RawYieldsDstar_ML_outFD_pos03.root,
            RawYieldsDstar_ML_outFD_pos04.root,
            RawYieldsDstar_ML_outFD_pos05.root,
            RawYieldsDstar_ML_outFD_pos06.root,
            RawYieldsDstar_ML_outFD_pos07.root,
            RawYieldsDstar_ML_outFD_pos08.root,
            RawYieldsDstar_ML_outFD_pos09.root,
            RawYieldsDstar_ML_outFD_pos10.root,
            RawYieldsDstar_ML_outFD_pos11.root,
            RawYieldsDstar_ML_outFD_pos12.root,
            RawYieldsDstar_ML_outFD_pos13.root
        ]
    histoname: hRawYields

efficiencies:
    inputdir: ../Analysis_output/HM_Opti0306_v161022/CutVar_Opti0306_small/
    inputfiles: [
            Eff_times_Acc_Dstar_ML_outFD_neg01.root,
            Eff_times_Acc_Dstar_ML_outFD_neg02.root,
            Eff_times_Acc_Dstar_ML_outFD_neg03.root,
            Eff_times_Acc_Dstar_ML_outFD_neg04.root,
            Eff_times_Acc_Dstar_ML_outFD_neg05.root,
            Eff_times_Acc_Dstar_ML_outFD_neg06.root,
            Eff_times_Acc_Dstar_ML_outFD_neg07.root,
            Eff_times_Acc_Dstar_ML_outFD_neg08.root,
            Eff_times_Acc_Dstar_ML_outFD_neg09.root,
            Eff_times_Acc_Dstar_ML_outFD_neg10.root,
            Eff_times_Acc_Dstar_ML_outFD_pos01.root,
            Eff_times_Acc_Dstar_ML_outFD_pos02.root,
            Eff_times_Acc_Dstar_ML_outFD_pos03.root,
            Eff_times_Acc_Dstar_ML_outFD_pos04.root,
            Eff_times_Acc_Dstar_ML_outFD_pos05.root,
            Eff_times_Acc_Dstar_ML_outFD_pos06.root,
            Eff_times_Acc_Dstar_ML_outFD_pos07.root,
            Eff_times_Acc_Dstar_ML_outFD_pos08.root,
            Eff_times_Acc_Dstar_ML_outFD_pos09.root,
            Eff_times_Acc_Dstar_ML_outFD_pos10.root,
            Eff_times_Acc_Dstar_ML_outFD_pos11.root,
            Eff_times_Acc_Dstar_ML_outFD_pos12.root,
            Eff_times_Acc_Dstar_ML_outFD_pos13.root
        ] #
    histonames:
        prompt: hAccEffPrompt
        feeddown: hAccEffFD

background: # needed only in case of smearing applied
    inputdir: ../Analysis_output/HM_Opti0306_v161022/CutVar_Opti0306_small/
    inputfiles: [
            RawYieldsDstar_ML_outFD_neg01.root,
            RawYieldsDstar_ML_outFD_neg02.root,
            RawYieldsDstar_ML_outFD_neg03.root,
            RawYieldsDstar_ML_outFD_neg04.root,
            RawYieldsDstar_ML_outFD_neg05.root,
            RawYieldsDstar_ML_outFD_neg06.root,
            RawYieldsDstar_ML_outFD_neg07.root,
            RawYieldsDstar_ML_outFD_neg08.root,
            RawYieldsDstar_ML_outFD_neg09.root,
            RawYieldsDstar_ML_outFD_neg10.root,
            RawYieldsDstar_ML_outFD_pos01.root,
            RawYieldsDstar_ML_outFD_pos02.root,
            RawYieldsDstar_ML_outFD_pos03.root,
            RawYieldsDstar_ML_outFD_pos04.root,
            RawYieldsDstar_ML_outFD_pos05.root,
            RawYieldsDstar_ML_outFD_pos06.root,
            RawYieldsDstar_ML_outFD_pos07.root,
            RawYieldsDstar_ML_outFD_pos08.root,
            RawYieldsDstar_ML_outFD_pos09.root,
            RawYieldsDstar_ML_outFD_pos10.root,
            RawYieldsDstar_ML_outFD_pos11.root,
            RawYieldsDstar_ML_outFD_pos12.root,
            RawYieldsDstar_ML_outFD_pos13.root
        ]
    histoname: hRawYieldsBkg

minimisation:
    correlated: true # true --> fully correlated, false --> fully uncorrelated
    doRawYieldSmearing: false # whether to smear the yields with a poissonian error
    setseed: false # set the seed for Poissonian smearing
    applyEffVariation:
        enable: false
        relvariation: 0.05
        option: decreasing # available options: [upshift, downshift, decreasing, increasing]
        prompt: true
        feeddown: true

linearplot:
    enable: true #enable linear plots NpromptVsNFD
    uncbands: true #enable upper/lower linear plots limits
    outfileformat: ["pdf"] # linear plot saved in different output formats (e.g. png, pdf, etc.). Plots are already saved in the ouput TFile

theorydriven:
    enableFc: false
    enableNb: false
    predictions:
        crosssec:
            inputfile: models/DmesonLcPredictions_13TeV_y05_FFptDepLHCb_BRpythia8_PDG2020_PromptLcMod.root
            histonames:
                prompt: hLcK0sppred_max
                feeddown: hLcK0spfromBpred_max_corr
        Raa:
            prompt: 1.
            feeddown: 1.
            model: tamu # avaliable models: 'phsd', 'Catania', 'tamu', 'MCatsHQ'
    # below only needed for Nb
    sigmaMB: 57.8e+9
